# **IS 362 - Project 2**

In [1]:
import pandas as pd

## Dataset 1 - Desserts Worldwide, by Cherubim-Ken Fonacier

In [2]:
desserts = pd.read_csv('Desserts_Worldwide.csv')
desserts

,Dessert Name,Dessert Category,Country/Region of Origin,Continent,Texture 1,Texture 2
0,Tiramisú,Custard,Italy,Europe,Creamy,NaN
1,Polvorónes,Cookie,Latin America,NaN,Crumbly,NaN
2,Polvorónes,Cookie,Spain,Europe,Crumbly,NaN
3,Polvorónes,Cookie,Philippines,Asia,Crumbly,NaN
4,New York Cheesecake,Cake,United States,North America,Creamy,Crumbly
5,Japanese Cheesecake,Cake,Japan,Asia,Creamy,Fluffy
6,Gâteau Fondant au Chocolat,Cake,France,Europe,Fluffy,Gooey
7,Gelato,Frozen,Italy,Europe,Creamy,NaN
8,Alfajores,Cookie,NaN,South America,Crumbly,Gooey
9,Baklava,Pastry,Turkey,Europe,Gooey,NaN
10,Borma,Pastry,Middle East,NaN,Crispy,NaN
11,Borma,Pastry,Turkey,Europe,Crispy,NaN
12,Crème Brûlée,Custard,France,Europe,Crispy,Creamy
13,Pavlova,Candy,Australia,Australia,Crunchy,Creamy
14,Pavlova,Candy,New Zealand,Australia,Crunchy,Creamy
15,Saffron Ice Cream,Frozen,Iran,Asia,Creamy,NaN
16,Trifle,Cake,United Kingdom,Europe,Fluffy,Creamy
17,Xue Hua Bing,Frozen,Taiwan,Asia,Crunchy,Creamy
18,Rigó Jancsi,Cake,Hungary,Europe,Fluffy,NaN
19,Mandazi,Pastry,South Sudan,Africa,Crispy,NaN
20,Lemon Tart,Pastry,France,Europe,Crumbly,NaN
21,Flan,Custard,Latin America,NaN,Creamy,NaN
22,Chocolate Chip Cookie,Cookie,United States,North America,Crumbly,NaN
23,Doughnut,Pastry,United States,North America,Chewy,NaN
24,Gulab Jamun,Pastry,India,Asia,Chewy,NaN
25,Oliebollen,Pastry,Netherlands,Europe,Crispy,Crunchy

To have cells with consecutive redundant values be merged as one, more than one series has to be made an index.

Though this cell below is purely for aesthetic purposes, and has no relevance to data analyses.

In [3]:
pd.read_csv('Desserts_Worldwide.csv', index_col=(0, 1, 2))

                                                                          Continent  \
Dessert Name               Dessert Category Country/Region of Origin
Tiramisú                   Custard          Italy                            Europe
Polvorónes                 Cookie           Latin America                       NaN
                                            Spain                            Europe
                                            Philippines                        Asia
New York Cheesecake        Cake             United States             North America
Japanese Cheesecake        Cake             Japan                              Asia
Gâteau Fondant au Chocolat Cake             France                           Europe
Gelato                     Frozen           Italy                            Europe
Alfajores                  Cookie           NaN                       South America
Baklava                    Pastry           Turkey                           Europe
Borma                      Pastry           Middle East                         NaN
                                            Turkey                           Europe
Crème Brûlée               Custard          France                           Europe
Pavlova                    Candy            Australia                     Australia
                                            New Zealand                   Australia
Saffron Ice Cream          Frozen           Iran                               Asia
Trifle                     Cake             United Kingdom                   Europe
Xue Hua Bing               Frozen           Taiwan                             Asia
Rigó Jancsi                Cake             Hungary                          Europe
Mandazi                    Pastry           South Sudan                      Africa
Lemon Tart                 Pastry           France                           Europe
Flan                       Custard          Latin America                       NaN
Chocolate Chip Cookie      Cookie           United States             North America
Doughnut                   Pastry           United States             North America
Gulab Jamun                Pastry           India                              Asia
Oliebollen                 Pastry           Netherlands                      Europe

                                                                     Texture 1  \
Dessert Name               Dessert Category Country/Region of Origin
Tiramisú                   Custard          Italy                       Creamy
Polvorónes                 Cookie           Latin America              Crumbly
                                            Spain                      Crumbly
                                            Philippines                Crumbly
New York Cheesecake        Cake             United States               Creamy
Japanese Cheesecake        Cake             Japan                       Creamy
Gâteau Fondant au Chocolat Cake             France                      Fluffy
Gelato                     Frozen           Italy                       Creamy
Alfajores                  Cookie           NaN                        Crumbly
Baklava                    Pastry           Turkey                       Gooey
Borma                      Pastry           Middle East                 Crispy
                                            Turkey                      Crispy
Crème Brûlée               Custard          France                      Crispy
Pavlova                    Candy            Australia                  Crunchy
                                            New Zealand                Crunchy
Saffron Ice Cream          Frozen           Iran                        Creamy
Trifle                     Cake             United Kingdom              Fluffy
Xue Hua Bing               Frozen           Taiwan                     Crunchy
Rigó Jancsi                Cake             Hungary                     Fluffy
Mandazi                    Pastry           South Sudan                 Crispy
Lemon Tart                 Pastry           France                     Crumbly
Flan                       Custard          Latin America               Creamy
Chocolate Chip Cookie      Cookie           United States              Crumbly
Doughnut                   Pastry           United States                Chewy
Gulab Jamun                Pastry           India                        Chewy
Oliebollen                 Pastry           Netherlands                 Crispy

                                                                     Texture 2
Dessert Name               Dessert Category Country/Region of Origin
Tiramisú                   Custard          Italy                          NaN
Polvorónes                 Cookie           Latin America                  NaN
                                            Spain                          NaN
                                            Philippines                    NaN
New York Cheesecake        Cake             United States              Crumbly
Japanese Cheesecake        Cake             Japan                       Fluffy
Gâteau Fondant au Chocolat Cake             France                       Gooey
Gelato                     Frozen           Italy                          NaN
Alfajores                  Cookie           NaN                          Gooey
Baklava                    Pastry           Turkey                         NaN
Borma                      Pastry           Middle East                    NaN
                                            Turkey                         NaN
Crème Brûlée               Custard          France                      Creamy
Pavlova                    Candy            Australia                   Creamy
                                            New Zealand                 Creamy
Saffron Ice Cream          Frozen           Iran                           NaN
Trifle                     Cake             United Kingdom              Creamy
Xue Hua Bing               Frozen           Taiwan                      Creamy
Rigó Jancsi                Cake             Hungary                        NaN
Mandazi                    Pastry           South Sudan                    NaN
Lemon Tart                 Pastry           France                         NaN
Flan                       Custard          Latin America                  NaN
Chocolate Chip Cookie      Cookie           United States                  NaN
Doughnut                   Pastry           United States                  NaN
Gulab Jamun                Pastry           India                          NaN
Oliebollen                 Pastry           Netherlands                Crunchy

## Analyses

### What dessert(s) have more than one occurrence in the DataFrame? Or rather, what desserts come from multiple countries/regions? 
These multiple occurrences indicate that these desserts are shared among different cultures.

The 'value_counts()' function counts the number of occurrences based on its series. If there are mulitple of the same value in a series, this function will identify how many times it occurs.

In [4]:
shared = desserts['Dessert Name'].value_counts()
multicultural = pd.DataFrame(shared)
multicultural.columns = ['Countries/Regions Present']
multicultural[multicultural['Countries/Regions Present'] > 1]

            Countries/Regions Present
Polvorónes                          3
Borma                               2
Pavlova                             2

### Answer:

**Polvorónes**, **Borma**, and **Pavlova** are the desserts that have more than one occurrence in the DataFrame. Thus, these desserts are shared among different cultures.

The cell below sorts all of the desserts alphabetically

In [5]:
desserts.sort_values('Dessert Name')

,Dessert Name,Dessert Category,Country/Region of Origin,Continent,Texture 1,Texture 2
8,Alfajores,Cookie,NaN,South America,Crumbly,Gooey
9,Baklava,Pastry,Turkey,Europe,Gooey,NaN
10,Borma,Pastry,Middle East,NaN,Crispy,NaN
11,Borma,Pastry,Turkey,Europe,Crispy,NaN
22,Chocolate Chip Cookie,Cookie,United States,North America,Crumbly,NaN
12,Crème Brûlée,Custard,France,Europe,Crispy,Creamy
23,Doughnut,Pastry,United States,North America,Chewy,NaN
21,Flan,Custard,Latin America,NaN,Creamy,NaN
7,Gelato,Frozen,Italy,Europe,Creamy,NaN
24,Gulab Jamun,Pastry,India,Asia,Chewy,NaN
6,Gâteau Fondant au Chocolat,Cake,France,Europe,Fluffy,Gooey
5,Japanese Cheesecake,Cake,Japan,Asia,Creamy,Fluffy
20,Lemon Tart,Pastry,France,Europe,Crumbly,NaN
19,Mandazi,Pastry,South Sudan,Africa,Crispy,NaN
4,New York Cheesecake,Cake,United States,North America,Creamy,Crumbly
25,Oliebollen,Pastry,Netherlands,Europe,Crispy,Crunchy
14,Pavlova,Candy,New Zealand,Australia,Crunchy,Creamy
13,Pavlova,Candy,Australia,Australia,Crunchy,Creamy
3,Polvorónes,Cookie,Philippines,Asia,Crumbly,NaN
2,Polvorónes,Cookie,Spain,Europe,Crumbly,NaN
1,Polvorónes,Cookie,Latin America,NaN,Crumbly,NaN
18,Rigó Jancsi,Cake,Hungary,Europe,Fluffy,NaN
15,Saffron Ice Cream,Frozen,Iran,Asia,Creamy,NaN
0,Tiramisú,Custard,Italy,Europe,Creamy,NaN
16,Trifle,Cake,United Kingdom,Europe,Fluffy,Creamy
17,Xue Hua Bing,Frozen,Taiwan,Asia,Crunchy,Creamy

### What desserts originated in France?

In [6]:
desserts[desserts['Country/Region of Origin'] == 'France']

,Dessert Name,Dessert Category,Country/Region of Origin,Continent,Texture 1,Texture 2
6,Gâteau Fondant au Chocolat,Cake,France,Europe,Fluffy,Gooey
12,Crème Brûlée,Custard,France,Europe,Crispy,Creamy
20,Lemon Tart,Pastry,France,Europe,Crumbly,NaN

### Answer:

**Gâteau Fondant au Chocolat**, **Crème Brûlée**, and **Lemon Tart** are the desserts in the dataset that originated in France.

### Which desserts are considered to have a creamy texture?

In [7]:
desserts[(desserts['Texture 1'] == 'Creamy') | (desserts['Texture 2'] == 'Creamy')]

,Dessert Name,Dessert Category,Country/Region of Origin,Continent,Texture 1,Texture 2
0,Tiramisú,Custard,Italy,Europe,Creamy,NaN
4,New York Cheesecake,Cake,United States,North America,Creamy,Crumbly
5,Japanese Cheesecake,Cake,Japan,Asia,Creamy,Fluffy
7,Gelato,Frozen,Italy,Europe,Creamy,NaN
12,Crème Brûlée,Custard,France,Europe,Crispy,Creamy
13,Pavlova,Candy,Australia,Australia,Crunchy,Creamy
14,Pavlova,Candy,New Zealand,Australia,Crunchy,Creamy
15,Saffron Ice Cream,Frozen,Iran,Asia,Creamy,NaN
16,Trifle,Cake,United Kingdom,Europe,Fluffy,Creamy
17,Xue Hua Bing,Frozen,Taiwan,Asia,Crunchy,Creamy
21,Flan,Custard,Latin America,NaN,Creamy,NaN

### Answer:

**Tiramisú**, **New York Cheesecake**, **Japanese Cheesecake**, **Gelato**, **Crème Brûlée**, **Pavlova**, **Saffron Ice Cream**, **Trifle**, **Xue Hua Bing**, and **Flan** are the desserts to have creamy textures.

# Project Questions - Dataset 1

## Question 1: How much time did it take you to find the data set.  How much time then to clean it?

It took me at least a few hours to find the dataset, however, instead of a table, the information was in the form of a list. Thus, I had to create a dataset based on the information from the list, but with about 22 individual desserts of my choice. It took me about a day to "clean it," in which I had to create the dataset based on each dessert's characteristics, besides its names, I had to create columns/series based on what kind of dessert it was (e.g., custard, cake, frozen, candy, pastry), the country/region each of them originate from, the continent the country/region is in, and two separate columns for its textures.

## Question 2: What are some of the benefits that you created by preparing the dataset?

Some of the benefits I created by preparing the dataset was making it easier for the data to be parsed. The values in the dataset are rather simple, and these are characteristics that can be shared amongst them, besides their name. I initially planned to add a fully verbose description for each dessert, however, that data cannot be parsed as they are full strings of text and are unique to each dessert, so that idea was scrapped. Instead, I chose to simplify the dessert description based on characteristics, traits that define and assert their identity, while also enabling it easier to parse. However, not all of the row cells are filled as some desserts originate from a region not exclusively located in one continent (though in some cases, the opposite occurs; i.e., Alfajores), and not all desserts are considered to have more than one texture. Overall, the simplified characteristics listed as values makes it easier for the data to be tidied by software programs (e.g., Python, SQL, etc.).

## Question 3: What are some considerations you're taking in data preparation to maintain the data structure?

During the data preparation, I had to make sure that the dataset had variables/values that can be parsed. To reiterate, I initally was going to input a column with complete sentences describing each dessert. However, I realized that it would be too complicated and impossible to parse with the "sort_values()" statement. So instead, I opted to make single worded descriptions regarding the texture for each dessert, having two columns in case that the dessert in question has more than one primary texture. To maintain the data structure, I had to make sure I would have to make sure that all of the desserts listed had the same characteristics (e.g., texture(s), continent of origin, country/region of origin, etc.) so that when parsed, they would be sorted by a specific series/column.

## Dataset 2 - Mobile Device Management (MDM), by Ziwei Song

In [8]:
mdm = pd.read_csv('dummy_devices.csv')
mdm

,Device Name,Device Type,Operating Systems,Version,Owner,Username,MDM Compliance,Registration Time,Device Model
0,Laptop_05,Laptop,Windows,10.0.19044,Ruby Brewer,rb.wr@icloud.org,True,3/3/2022 15:40,Lenovo ThinkPad E16 Gen 2
1,Desktop_66,Desktop,Windows,10.0.19045,Fritz Spence,velit@yahoo.couk,True,6/13/2022 17:07,HP Z2 Mini G9
2,Griffin’s iPhones,Smartphone,iOS,17.5.1,Griffin Lambert,ac.feugiat@hotmail.com,True,9/23/2022 15:05,iPhone 11 Pro
3,Jade’s iPhone,Smartphone,iOS,17.6.1,Jade Rowe,eu.metus@protonmail.couk,True,9/23/2022 19:06,iPhone 12 Pro Max
4,Desktop_32,Desktop,Windows,11.0.26100,Salvador Nash,dignissim@yahoo.couk,True,12/8/2022 20:40,HP Z2 Mini G9
5,Desktop_01,Desktop,Windows,10.0.19045,NaN,NaN,NaN,12/11/2022 18:25,Lenovo ThinkCentre M710
6,Desktop_87,Desktop,Windows,11.0.22631,Simon English,sed.turpis@google.ca,True,12/12/2022 12:45,Dell OptiPlex 7000 Micro PC
7,Laptop_19,Laptop,Windows,10.0.19045,Mia Ayala,aenean@hotmail.couk,False,12/13/2022 13:15,Lenovo ThinkPad X1 Yoga Gen 8
8,Laptop_34,Laptop,Windows,10.0.19044,NaN,NaN,NaN,12/18/2022 0:01,NaN
9,Teagan’s iPhone,Smartphone,iOS,17.5.1,Teagan Serrano,facilisi.sed.neque@yahoo.edu,True,1/31/2023 16:24,iPhone 11
10,Kermit’s iPhone,Smartphone,iOS,17.6.1,Kermit Knapp,a.nunc.in@google.net,True,2/23/2023 17:59,iPhone 13 Pro Max
11,Sam’s iPad,Tablet,iPadOS,16.3.1,NaN,NaN,False,3/1/2023 19:32,iPad Air 1st
12,Ella’s iPad,Tablet,iPadOS,16.3.1,Ruby Brewer,rb.wr@icloud.org,False,3/2/2023 18:49,iPad Mini 3rd
13,Alex’s iPhone,Smartphone,iOS,17.6.1,Ginger Alexander,facilisis@hotmail.edu,True,3/28/2023 19:08,iPhone SE
14,Laptop_72,Laptop,Windows,10.0.19045,Fatima Fulton,ac.orci.ut@google.edu,False,5/8/2023 15:47,HP EliteBook 840 G9
15,iPhone 13,Smartphone,iOS,18,NaN,NaN,NaN,5/26/2023 10:03,NaN
16,Desktop_92,Desktop,Windows,11.0.22621,Cyrus Byers,interdum.curabitur@yahoo.net,True,6/13/2023 13:53,Dell OptiPlex 7000 Micro PC
17,Linsay_workphone,Smartphone,Android,11,Charlotte Lindsay,mauris@protonmail.org,False,8/14/2023 17:50,A600DL
18,Brynn’s iPhone,Smartphone,iOS,17.6.1,Brynn Mclaughlin,arcu.ac@icloud.org,True,8/30/2023 18:33,iPhone 12 Pro Max
19,samsung132,Smartphone,Android,13,NaN,NaN,NaN,9/21/2023 10:06,Samsung Galaxy S23
20,Kelly’s iPhone,Smartphone,iOS,17.5.1,Kelly Strickland,sem.pellentesque@google.couk,True,9/25/2023 14:18,iPhone 13
21,iPhone 12,Smartphone,iOS,17.6.1,NaN,NaN,NaN,10/4/2023 18:14,NaN
22,samsung62,Smartphone,Android,13,Kermit Knapp,a.nunc.in@google.net,True,10/8/2023 2:45,Samsung Galaxy S22 Ultra
23,samsungS11,Smartphone,Android,13,NaN,NaN,NaN,10/16/2023 16:40,Samsung Galaxy S23
24,Wood_AndroidForWork,Smartphone,Android,13,Lilah Wood,erat.in.consectetuer@yahoo.com,False,10/20/2023 4:56,Samsung Galaxy S22 Ultra
25,LAPTOP-Marvin,Laptop,Windows,11.0.22621,Marvin Kaufman,nulla.facilisis@icloud.couk,False,10/23/2023 1:06,HP EliteBook 840 G9
26,iPhone 13 Pro Max,Smartphone,iOS,17.6.1,NaN,NaN,NaN,10/24/2023 1:48,NaN
27,Tablet_19,Tablet,Windows,10.0.19045,Tasha Barrera,pede.nonummy@google.edu,True,10/30/2023 14:06,Dell Precision 5690
28,Anna_IPad_AIR,Tablet,iPadOS,16.3.1,Jade Rowe,eu.metus@protonmail.couk,False,11/6/2023 14:11,iPad Air 4th
29,iPhone 14 Pro Max,Smartphone,iOS,17.4.1,NaN,NaN,NaN,11/18/2023 15:56,NaN
30,Tablet_68,Tablet,Windows,10.0.19045,Ivor Gentry,tortor.nibh.sit@aol.couk,True,12/8/2023 20:39,Dell Precision 5690
31,Laptop_655,Laptop,Windows,10.0.19045,Stacey Wise,orci.quis@icloud.net,True,1/11/2024 23:08,Lenovo ThinkPad E14 Gen 5
32,Tablet_74,Tablet,Windows,11.0.22000,Octavius Gates,interdum.curabitur@hotmail.com,True,2/16/2024 17:44,Dell Precision 5690
33,iPhone 13 Pro Max,Smartphone,iOS,17.7,NaN,NaN,NaN,2/16/2024 21:57,NaN
34,iPhone,Smartphone,iOS,17.6.1,Sade Powell,amet@hotmail.com,True,2/28/2024 21:14,iPhone 13
35,iPad,Tablet,iPadOS,17.4,Amela Gonzalez,mi.lacinia@hotmail.couk,False,3/26/2024 17:47,iPadPro 6th
36,iPad,Tablet,iPadOS,17.5.1,Wynter Torres,nulla@outlook.ca,False,3/27/2024 14:49,iPad Air 5th
37,Chang's Android,Smartphone,Android,12,Lunea Chang,leo.in@outlook.couk,True,5/2/2024 14:06,Google Pixel 8a
38,Jasper's Android,Smartphone,Android,12,Jasper Gross,primis@hotmail.net,True,5/2/2024 16:46,OnePlus 12R
39,Bell Workphone,Smartphone,Android,12,Akeem Bell,vulputate.lacus.cras@outlook.couk,True,5/2/2024 18:33,Samsung Galaxy A15
40,Arnold phone,Smartphone,Android,12,Ima Arnold,blandit.nam@outlook.couk,True,5/10/2024 19:58,Google Pixel 9 Pro
41,DK cellphone,Smartphone,Android,12,Delilah Kerr,nec.mauris@protonmail.com,True,5/21/2024 14:36,Samsung Galaxy S24 Ultra
42,Moon,Smartphone,Android,12,Haviva Moon,et.rutrum@aol.com,True,5/23/2024 14:26,Samsung Galaxy A15
43,Lydia’s iPhone,Smartphone,iOS,17.5.1,Lydia Berg,ac.mattis@icloud.com,False,7/19/2024 18:38,iPhone 12
44,Desktop_71,Desktop,Windows,10.0.19045,Mariam Maldonado,faucibus.lectus.a@protonmail.couk,True,8/16/2024 19:37,HP Z2 Mini G9
45,iPhone 14 Pro Max,Smartphone,iOS,18.1,Simon English,sed.turpis@google.ca,NaN,9/18/2024 11:48,iPhone 14 Pro Max

To clean up and tidy the data, I would first have to remove all of the rows with devices that have no owners or emails registered. Devices that have no owners thus do not meet the MDM compliance requirements and should not have  access to the organization's data and resources. To do this, I would have to use the "dropna.()" function to remove all of those rows. Also, I would have to specify that it only drops the rows that have "NaN" values for the "Owner" and "Username" columns only. This is because one person, Simon English, has an iPhone 14 Pro Max registered to the system, but it is not recorded whether or not the device is MDM compliant, as there is no value for it present. Judging by the lack of a customized name for the device, it can be assumed that the device is either new or underwent a factory reset; though it is more likely the former as it has the newest version of iOS installed.

In [9]:
clean_mdm = mdm.dropna(subset=['Owner', 'Username'])
clean_mdm

,Device Name,Device Type,Operating Systems,Version,Owner,Username,MDM Compliance,Registration Time,Device Model
0,Laptop_05,Laptop,Windows,10.0.19044,Ruby Brewer,rb.wr@icloud.org,True,3/3/2022 15:40,Lenovo ThinkPad E16 Gen 2
1,Desktop_66,Desktop,Windows,10.0.19045,Fritz Spence,velit@yahoo.couk,True,6/13/2022 17:07,HP Z2 Mini G9
2,Griffin’s iPhones,Smartphone,iOS,17.5.1,Griffin Lambert,ac.feugiat@hotmail.com,True,9/23/2022 15:05,iPhone 11 Pro
3,Jade’s iPhone,Smartphone,iOS,17.6.1,Jade Rowe,eu.metus@protonmail.couk,True,9/23/2022 19:06,iPhone 12 Pro Max
4,Desktop_32,Desktop,Windows,11.0.26100,Salvador Nash,dignissim@yahoo.couk,True,12/8/2022 20:40,HP Z2 Mini G9
6,Desktop_87,Desktop,Windows,11.0.22631,Simon English,sed.turpis@google.ca,True,12/12/2022 12:45,Dell OptiPlex 7000 Micro PC
7,Laptop_19,Laptop,Windows,10.0.19045,Mia Ayala,aenean@hotmail.couk,False,12/13/2022 13:15,Lenovo ThinkPad X1 Yoga Gen 8
9,Teagan’s iPhone,Smartphone,iOS,17.5.1,Teagan Serrano,facilisi.sed.neque@yahoo.edu,True,1/31/2023 16:24,iPhone 11
10,Kermit’s iPhone,Smartphone,iOS,17.6.1,Kermit Knapp,a.nunc.in@google.net,True,2/23/2023 17:59,iPhone 13 Pro Max
12,Ella’s iPad,Tablet,iPadOS,16.3.1,Ruby Brewer,rb.wr@icloud.org,False,3/2/2023 18:49,iPad Mini 3rd
13,Alex’s iPhone,Smartphone,iOS,17.6.1,Ginger Alexander,facilisis@hotmail.edu,True,3/28/2023 19:08,iPhone SE
14,Laptop_72,Laptop,Windows,10.0.19045,Fatima Fulton,ac.orci.ut@google.edu,False,5/8/2023 15:47,HP EliteBook 840 G9
16,Desktop_92,Desktop,Windows,11.0.22621,Cyrus Byers,interdum.curabitur@yahoo.net,True,6/13/2023 13:53,Dell OptiPlex 7000 Micro PC
17,Linsay_workphone,Smartphone,Android,11,Charlotte Lindsay,mauris@protonmail.org,False,8/14/2023 17:50,A600DL
18,Brynn’s iPhone,Smartphone,iOS,17.6.1,Brynn Mclaughlin,arcu.ac@icloud.org,True,8/30/2023 18:33,iPhone 12 Pro Max
20,Kelly’s iPhone,Smartphone,iOS,17.5.1,Kelly Strickland,sem.pellentesque@google.couk,True,9/25/2023 14:18,iPhone 13
22,samsung62,Smartphone,Android,13,Kermit Knapp,a.nunc.in@google.net,True,10/8/2023 2:45,Samsung Galaxy S22 Ultra
24,Wood_AndroidForWork,Smartphone,Android,13,Lilah Wood,erat.in.consectetuer@yahoo.com,False,10/20/2023 4:56,Samsung Galaxy S22 Ultra
25,LAPTOP-Marvin,Laptop,Windows,11.0.22621,Marvin Kaufman,nulla.facilisis@icloud.couk,False,10/23/2023 1:06,HP EliteBook 840 G9
27,Tablet_19,Tablet,Windows,10.0.19045,Tasha Barrera,pede.nonummy@google.edu,True,10/30/2023 14:06,Dell Precision 5690
28,Anna_IPad_AIR,Tablet,iPadOS,16.3.1,Jade Rowe,eu.metus@protonmail.couk,False,11/6/2023 14:11,iPad Air 4th
30,Tablet_68,Tablet,Windows,10.0.19045,Ivor Gentry,tortor.nibh.sit@aol.couk,True,12/8/2023 20:39,Dell Precision 5690
31,Laptop_655,Laptop,Windows,10.0.19045,Stacey Wise,orci.quis@icloud.net,True,1/11/2024 23:08,Lenovo ThinkPad E14 Gen 5
32,Tablet_74,Tablet,Windows,11.0.22000,Octavius Gates,interdum.curabitur@hotmail.com,True,2/16/2024 17:44,Dell Precision 5690
34,iPhone,Smartphone,iOS,17.6.1,Sade Powell,amet@hotmail.com,True,2/28/2024 21:14,iPhone 13
35,iPad,Tablet,iPadOS,17.4,Amela Gonzalez,mi.lacinia@hotmail.couk,False,3/26/2024 17:47,iPadPro 6th
36,iPad,Tablet,iPadOS,17.5.1,Wynter Torres,nulla@outlook.ca,False,3/27/2024 14:49,iPad Air 5th
37,Chang's Android,Smartphone,Android,12,Lunea Chang,leo.in@outlook.couk,True,5/2/2024 14:06,Google Pixel 8a
38,Jasper's Android,Smartphone,Android,12,Jasper Gross,primis@hotmail.net,True,5/2/2024 16:46,OnePlus 12R
39,Bell Workphone,Smartphone,Android,12,Akeem Bell,vulputate.lacus.cras@outlook.couk,True,5/2/2024 18:33,Samsung Galaxy A15
40,Arnold phone,Smartphone,Android,12,Ima Arnold,blandit.nam@outlook.couk,True,5/10/2024 19:58,Google Pixel 9 Pro
41,DK cellphone,Smartphone,Android,12,Delilah Kerr,nec.mauris@protonmail.com,True,5/21/2024 14:36,Samsung Galaxy S24 Ultra
42,Moon,Smartphone,Android,12,Haviva Moon,et.rutrum@aol.com,True,5/23/2024 14:26,Samsung Galaxy A15
43,Lydia’s iPhone,Smartphone,iOS,17.5.1,Lydia Berg,ac.mattis@icloud.com,False,7/19/2024 18:38,iPhone 12
44,Desktop_71,Desktop,Windows,10.0.19045,Mariam Maldonado,faucibus.lectus.a@protonmail.couk,True,8/16/2024 19:37,HP Z2 Mini G9
45,iPhone 14 Pro Max,Smartphone,iOS,18.1,Simon English,sed.turpis@google.ca,NaN,9/18/2024 11:48,iPhone 14 Pro Max

### Who has an MDM compliant PC (Laptop or Desktop) that runs on the latest Windows OS?

In [10]:
pc_sort = clean_mdm[clean_mdm['Operating Systems'] == 'Windows']
pc_sort.sort_values('Version', ascending=False)

,Device Name,Device Type,Operating Systems,Version,Owner,Username,MDM Compliance,Registration Time,Device Model
4,Desktop_32,Desktop,Windows,11.0.26100,Salvador Nash,dignissim@yahoo.couk,True,12/8/2022 20:40,HP Z2 Mini G9
6,Desktop_87,Desktop,Windows,11.0.22631,Simon English,sed.turpis@google.ca,True,12/12/2022 12:45,Dell OptiPlex 7000 Micro PC
16,Desktop_92,Desktop,Windows,11.0.22621,Cyrus Byers,interdum.curabitur@yahoo.net,True,6/13/2023 13:53,Dell OptiPlex 7000 Micro PC
25,LAPTOP-Marvin,Laptop,Windows,11.0.22621,Marvin Kaufman,nulla.facilisis@icloud.couk,False,10/23/2023 1:06,HP EliteBook 840 G9
32,Tablet_74,Tablet,Windows,11.0.22000,Octavius Gates,interdum.curabitur@hotmail.com,True,2/16/2024 17:44,Dell Precision 5690
1,Desktop_66,Desktop,Windows,10.0.19045,Fritz Spence,velit@yahoo.couk,True,6/13/2022 17:07,HP Z2 Mini G9
7,Laptop_19,Laptop,Windows,10.0.19045,Mia Ayala,aenean@hotmail.couk,False,12/13/2022 13:15,Lenovo ThinkPad X1 Yoga Gen 8
14,Laptop_72,Laptop,Windows,10.0.19045,Fatima Fulton,ac.orci.ut@google.edu,False,5/8/2023 15:47,HP EliteBook 840 G9
27,Tablet_19,Tablet,Windows,10.0.19045,Tasha Barrera,pede.nonummy@google.edu,True,10/30/2023 14:06,Dell Precision 5690
30,Tablet_68,Tablet,Windows,10.0.19045,Ivor Gentry,tortor.nibh.sit@aol.couk,True,12/8/2023 20:39,Dell Precision 5690
31,Laptop_655,Laptop,Windows,10.0.19045,Stacey Wise,orci.quis@icloud.net,True,1/11/2024 23:08,Lenovo ThinkPad E14 Gen 5
44,Desktop_71,Desktop,Windows,10.0.19045,Mariam Maldonado,faucibus.lectus.a@protonmail.couk,True,8/16/2024 19:37,HP Z2 Mini G9
0,Laptop_05,Laptop,Windows,10.0.19044,Ruby Brewer,rb.wr@icloud.org,True,3/3/2022 15:40,Lenovo ThinkPad E16 Gen 2

To find the answer, I had to first filter the data that ran on the Windows OS, and then sort out the values of the version of the OS, but the values had to descend so that the latest version would appear on the first few rows. Thus, it would show the full details of the registered device: the owners, the device model, and whether or not it is MDM compliant.

### Answer:

**Salvador Nash** has an MDM compliant desktop that runs on the latest Windows OS, Version 11.0.26100, on an HP Z2 Mini G9.

### Who has mulitple devices registered into organization's system?

In order to determine this, I would have to count all of the occurrences of names that appear in the dataset. As the same name registered for multiple devices would indicate that the person has multiple ways to access the system, working across devices. On the dataset, this would be shown if a value for "Owner" occurs more than once.

In [11]:
multi_device = clean_mdm['Owner'].value_counts()
devices = pd.DataFrame(multi_device)
devices.columns = ['Devices Owned']
devices[devices['Devices Owned'] > 1]

               Devices Owned
Ruby Brewer                2
Jade Rowe                  2
Simon English              2
Kermit Knapp               2

### Answer:

**Ruby Brewer**, **Jade Rowe**, **Simon English**, **Kermit Knapp** are the people that have multiple devices registered and have access to the organization's IT infrastructure.

# Project Questions - Dataset 2

## Question 1: How much time did it take you to find the data set.  How much time then to clean it?

I only found this dataset for an hour, since it was posted by the original creator on the Discussion Board. However, it took me about thirty minutes at least to clean it based on the suggestions provided, having to separate the concatenated data into two separate columns and fix some values with incorrect names. For the former, it was the operating system for each device, I had to separate the type of OS it was followed by the version number for it. Secondly, I had to fix some values that had incorrect names for the operating systems, such as those that originally had lowercase names (e.g., 'samsung'), which can be problematic when retrieving or filtering data, as well as for some people being particular to type case-sensitive terms. After cleaning the CSV, I imported it into Jupyter, where I did more cleaning by dropping rows that had null values in the "Owner" and "Username" columns.

## Question 2: What are some of the benefits that you created by preparing the dataset?

Some of the benefits I created by preparing the dataset was making it easier for it to parse. When retrieving data using command on Jupyter Notebook, the value is case sensitive. I had to make some adjustments from the original file that Ziwei provided. For the Operating System for each device, it was easy to separate the values into two separate columns, being the type of OS and its version number. I also had to fix the type of OS for the devices to proper names, fixing the uppercase and lowercase letters for Operating System names, making it easier for devices to share the same characteristics when filtering or sorting them. Thus, when retrieving the data based on those desired variables, with terms that most people would be familiar with, anyone will be able to easily parse through the information in the dataset.

Plus, the object "clean_mdm" drops the unnecessary rows not containing either a name or username/email, as those rows contain information for devices that are automatically considered non-compliant MDM devices.

## Question 3: What are some considerations you're taking in data preparation to maintain the data structure?

Some considerations I took in data preparation to maintain the data structure was ensuring that the majority of the data in the original CSV file remained the same. The number of rows were maintained as I added a column to distinguish between a device's type of operating system (OS) and its version number. Concatenated values would be difficult to parse, so they would have to be separated to simplify things. The corrections to the names of the operating systems were necessary as technologically-adept people will not know the OS by those terms and the "I" in "iPhone" and "iPad" are meant to be lowercase. Plus, people may be incorrectly informed by those terms. After making adjustments to make it easier for parsing the dataset, I proceeded to drop the rows that lack values for "Person" and "Username," with the object "clean_mdm" as those rows of data are irrelevant.

Thus, these changes make it easier for untidy data to be parsed and sorted in database programs, with more specified - yet shared - characteristics, while still maintaining the original data structure.

## Dataset 3 - Software Company Employee Data

In [12]:
employee_info = pd.read_csv('Software_Company_Employees.csv')
employee_info

,Name,Position,Office,Age,Start date
0,Airi Satou,Accountant,Tokyo,33,11/27/2008
1,Angelica Ramos,Chief Executive Officer (CEO),London,47,10/8/2009
2,Ashton Cox,Junior Technical Author,San Francisco,66,1/11/2009
3,Bradley Greer,Software Engineer,London,41,10/12/2012
4,Brenden Wagner,Software Engineer,San Francisco,28,6/6/2011
5,Brielle Williamson,Integration Specialist,New York,61,12/1/2012
6,Bruno Nash,Software Engineer,London,38,5/2/2011
7,Caesar Vance,Pre-Sales Support,New York,21,12/11/2011
8,Cara Stevens,Sales Assistant,New York,46,12/5/2011
9,Cedric Kelly,Senior Javascript Developer,Edinburgh,22,3/28/2012
10,Charde Marshall,Regional Director,San Francisco,36,10/15/2008
11,Colleen Hurst,Javascript Developer,San Francisco,39,9/14/2009
12,Dai Rios,Personnel Lead,Edinburgh,35,9/25/2012
13,Donna Snider,Customer Support,New York,27,1/24/2011
14,Doris Wilder,Sales Assistant,Sydney,23,9/19/2010
15,Finn Camacho,Support Engineer,San Francisco,47,7/6/2009
16,Fiona Green,Chief Operating Officer (COO),San Francisco,48,3/10/2010
17,Garrett Winters,Accountant,Tokyo,63,7/24/2011
18,Gavin Cortez,Team Leader,San Francisco,22,10/25/2008
19,Gavin Joyce,Developer,Edinburgh,42,12/21/2010
20,Gloria Little,Systems Administrator,New York,59,4/9/2009
21,Haley Kennedy,Senior Marketing Designer,London,43,12/17/2012
22,Hermione Butler,Regional Director,London,47,3/20/2011
23,Herrod Chandler,Sales Assistant,San Francisco,59,8/5/2012
24,Hope Fuentes,Secretary,San Francisco,41,2/11/2010
25,Howard Hatfield,Office Manager,San Francisco,51,12/15/2008
26,Jackson Bradshaw,Director,New York,65,9/25/2008
27,Jena Gaines,Office Manager,London,30,12/18/2008
28,Jenette Caldwell,Development Lead,New York,30,9/2/2011
29,Jennifer Acosta,Junior Javascript Developer,Edinburgh,43,1/31/2013
30,Jennifer Chang,Regional Director,Singapore,28,11/13/2010
31,Jonas Alexander,Developer,San Francisco,30,7/13/2010
32,Lael Greer,Systems Administrator,London,21,2/26/2009
33,Martena Mccray,Post-Sales support,Edinburgh,46,3/8/2011
34,Michael Bruce,Javascript Developer,Singapore,29,6/26/2011
35,Michael Silva,Marketing Designer,London,66,11/26/2012
36,Michelle House,Integration Specialist,Sydney,37,6/1/2011
37,Olivia Liang,Support Engineer,Singapore,64,2/2/2011
38,Paul Byrd,Chief Financial Officer (CFO),New York,64,6/8/2010
39,Prescott Bartlett,Technical Author,London,27,5/6/2011
40,Quinn Flynn,Support Lead,Edinburgh,22,3/2/2013
41,Rhona Davidson,Integration Specialist,Tokyo,55,10/13/2010
42,Sakura Yamamoto,Support Engineer,Tokyo,37,8/18/2009
43,Serge Baldwin,Data Coordinator,Singapore,64,4/8/2012
44,Shad Decker,Regional Director,Edinburgh,51,11/12/2008
45,Shou Itou,Regional Marketing,Tokyo,20,8/13/2011
46,Sonya Frost,Software Engineer,Edinburgh,23,12/12/2008
47,Suki Burks,Developer,London,53,10/21/2009
48,Tatyana Fitzpatrick,Regional Director,London,19,3/16/2010
49,Thor Walton,Developer,New York,61,8/10/2013
50,Tiger Nixon,System Architect,Edinburgh,61,4/24/2011
51,Timothy Mooney,Office Manager,London,37,12/10/2008
52,Unity Butler,Marketing Designer,San Francisco,47,12/8/2009
53,Vivian Harrell,Financial Controller,San Francisco,62,2/13/2009
54,Yuri Berry,Chief Marketing Officer (CMO),New York,40,6/24/2009
55,Zenaida Frank,Software Engineer,New York,63,1/3/2010
56,Zorita Serrano,Software Engineer,San Francisco,56,5/31/2012

### Who is the youngest Software Engineer in the entire corporation? Where are they stationed?

In [13]:
software_engineer = employee_info[employee_info['Position'] == 'Software Engineer']
young_se = software_engineer.sort_values('Age')
young_se

              Name           Position         Office  Age  Start date
46     Sonya Frost  Software Engineer      Edinburgh   23  12/12/2008
4   Brenden Wagner  Software Engineer  San Francisco   28    6/6/2011
6       Bruno Nash  Software Engineer         London   38    5/2/2011
3    Bradley Greer  Software Engineer         London   41  10/12/2012
56  Zorita Serrano  Software Engineer  San Francisco   56   5/31/2012
55   Zenaida Frank  Software Engineer       New York   63    1/3/2010

To be able to find the answer for this, I would first have to filter out the software engineers in the company from the "Position" series, creating an object ("software_engineer") out of the expression to do so. Afterwards, I would create another object ("young_se") to sort out the employees based on their age with ascending values. The first row would have the lowest value present, that being the software enginer who is the youngest amongst them, along with other information about them.

### Answer:

The youngest software engineer in the entire corporation is **Sonya Frost**, stationed in **Edinburgh, Scotland**.

### Who was employed at the corporation the longest? Or rather, who has the earliest start date?

The person who has the earliest start date is the one who has been employed at the company for the longest. Thus, to find the answer, the data would be parsed and sorted base on the series, "Start date." However, before using the 'sort_values()' function, the date values would have to be converted to datetime datatype objects with 'pd.to_datetime(). Afterwards, then the values in the dataset can be sorted, with the earliest employee being in the first row in the dataframe.

In [14]:
employee_info['Start date'] = pd.to_datetime(employee_info['Start date'])

employee_info.sort_values('Start date').head()

                Name           Position         Office  Age Start date
26  Jackson Bradshaw           Director       New York   65 2008-09-25
10   Charde Marshall  Regional Director  San Francisco   36 2008-10-15
18      Gavin Cortez        Team Leader  San Francisco   22 2008-10-25
44       Shad Decker  Regional Director      Edinburgh   51 2008-11-12
0         Airi Satou         Accountant          Tokyo   33 2008-11-27

### Answer:

**Jackson Bradshaw**, the **Director** of the corporation, has been employed the longest, located at the New York office. He has been at the corporation since **September 25, 2008**.

# Project Questions - Dataset 3

## Question 1: How much time did it take you to find the data set.  How much time then to clean it?

It only took me a few minutes to find the dataset on a website, here: https://datatables.net/, in which the data was based on positions in a corporation, which operates internationally as there are offices in different cities across the globe. I chose to use all of the entries present on the table, copy it to an Excel file, and then convert it into a CSV. There was not much to clean as the structure was mostly proper. However, to parse the values in the 'Start date' column, I had to convert the dates to datetime objects.

## Question 2: What are some of the benefits that you created by preparing the dataset?

Some of the benefits I created when preparing the dataset was making it easier to parse, especially for the date values. Having the dates as values would not work, they would instead have to be converted to datetime values/objects. If I were to try and sort the values of the date without converting them to datetime objects, they would instead be sorted based on the first digit, treating the dates as if they were a string of text instead. To remedy this, converting them to datetime objects would make it possible for them to be sorted.

As for the other series/columns and their values, they can be sorted with Jupyter Notebook as normal, no adjustments were needed.

## Question 3: What are some considerations you're taking in data preparation to maintain the data structure?

Some considerations I took in data preparation for this dataset was whether the data was parsable, and it was. However, the date values could not be sorted as intended as they would recognized as strongs of text, hence, converting them to datetime objects was a necessity. Plus, for variety, the size of the dataset had to be large in order to easily parse through, filter through, and retrieve from it, so I decided to use all of the rows that were present in the table from the website. This is because a small dataset (e.g., 5-10 rows) would be too easy to draw conclusions from, as the purpose of the Jupyter Notebook is to perform functions on a large dataframe.

Overall, aside from converting the date values in 'start date', the data structure was retained.

# Final Question (for all datasets):

## Question 4: If you did not use Python, what tool would you have used, how long would it have taken, and which do you prefer?

If I did not use Python (or Jupyter Notebook to an extent), I probably would have used SQL instead, or rather **MySQL Database** to be specific. I'm unsure how long it would have taken, as I would have to re-learn how MySQL operates and the required lines of text required to interact with the CSV. By my estimation, I believe it would have taken at least 1-2 days. 

Despite this, using MySQL has been complicated as it often required me to write a filepath to the CSV file I desired to interact with. Plus, I also experienced some complications on exporting and importing CSV files when working with them in SQL (though this may be in part of working from a Virtual Machine (VM)). Python (and Jupyter Notebook by extension) has not given me such problems when working with CSV files, regardless of whether it is stored locally or on GitHub. Thus, I strongly prefer **Python / Jupyter Notebook** when working with datasets.